name: Toolchain-cache-temp
on:
  # schedule:
  #   - cron: '51 10 28 * *'
  # runs at 10:51 UTC every 28th day of each month
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug session enabled'
        required: false
        default: false
        type: boolean

jobs:
  build:
    if: ${{ true }}
    name: Builds toolchain
    runs-on: ubuntu-latest
    container: alpine:edge
    defaults:
      run:
        shell: bash
    steps:
    - name: "⏬ Download tools"
      if: ${{ job.container }}
      shell: sh
      run: |
        apk update && apk upgrade
        apk add bash nano-syntax iproute2 util-linux-misc iproute2 \
          build-base linux-headers python3 cmake file git make tar xz curl jq
        # set PATH like in Ubuntu
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        # this seems to be needed when running in a container (beause of UID mismatch??)
        git config --global --add safe.directory '*'
        
    - name: "🔧 Prepare debug session"
      if: github.event.inputs.debug_enabled == 'true'
      run: |
        wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
        chmod +x /usr/local/bin/oh-my-posh
        wget -q https://github.com/okibcn/miniU/raw/main/Github_Linux/.nanorc -O /etc/nanorc
        wget -q https://github.com/okibcn/miniU/raw/main/Github_Linux/profile.sh -O ~/.zshrc
        cat ~/.zshrc >> ~/.bashrc 

    - name: "🐞 Debug session"
      uses: mxschmitt/action-tmate@v3
      if: github.event.inputs.debug_enabled == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ## More info at https://til.simonwillison.net/github-actions/debug-tmate
        ##           or https://github.com/mxschmitt/action-tmate

    - name: "📦 get package"
      run: |
        wget https://github.com/okibcn/nano-for-windows/releases/download/v7.2-8-10163.1/llvm-mingw.tar.xz

    - name: "🚮 Recycle Cache"
      uses: snnaplab/delete-branch-cache-action@v1

    - name: "💾 Save Build Folder"
      uses: actions/cache@v3.2.6
      id: cache-folder
      with:
        key: llvm-folder
        path: llvm-mingw/*

    - name: "💾 Save Build tar.xz"
      uses: actions/cache@v3.2.6
      id: cache-package
      with:
        key: llvm-txz
        path: llvm-mingw.tar.xz

    - name: "📃 list Caches"
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/actions/caches